linters:
  enable-all: true
  disable:
    - gci
    - exhaustivestruct

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
        - paralleltest

  include:
    - EXC0002 # disable excluding of issues about comments from golint
