name: Go

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get
      run: go get -v -t -d ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        version: v1.32
        args: -v ./...
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -coverprofile=/dev/null -v ./...
